/**
 * generate-bright-star-catalog.ts
 *
 * Extracts the NAAP skyMap028 bright-star catalog from the decompiled Flash
 * ActionScript and converts each star's spatial-partition data into equatorial
 * coordinates (RA hours, Dec degrees, visual magnitude).
 *
 * The decompiled `Bright Star Catalog.as` stores stars in a 2-level disc tree:
 * each sub-disc has a center unit vector {x,y,z}, a 3×3 rotation matrix
 * {w0..w8} (columns = local-x, local-y, normal=disc-center), and stars with
 * pre-projected local pixel coords {sx, sy, mag} at sphere radius R=250.
 *
 * Recovery (verified to <0.01° against Sirius, Vega, Capella, …):
 *   R = 1000  (= _scale × 100 / (_scale/10); disc MC _xscale is a Flash percentage)
 *   nx = −sx / R,  ny = −sy / R   (both axes sign-flipped: Flash y-down + disc handedness)
 *   nz = sqrt(max(0, 1 − nx² − ny²))
 *   worldX = w0·nx + w1·ny + w2·nz
 *   worldY = w3·nx + w4·ny + w5·nz
 *   worldZ = w6·nx + w7·ny + w8·nz
 *   raHours = atan2(worldY, worldX) · 12 / π   (normalized [0, 24))
 *   decDeg  = asin(worldZ) · 180 / π
 *
 * Run: npx tsx scripts/generate-bright-star-catalog.ts
 * Output: src/celestial/model/BrightStarCatalog.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const SOURCE = resolve(repoRoot, "NAAP/decompiled/skyMap028/scripts/%3Cdefault package%3E/Bright Star Catalog.as");
const OUTPUT = resolve(repoRoot, "src/celestial/model/BrightStarCatalog.ts");

const SPHERE_RADIUS = 1000; // disc MC _xscale = _scale/10 = 25 (percent → 0.25×); R = _scale/0.25 = 1000
const RAD_TO_HOURS = 12 / Math.PI;
const RAD_TO_DEG = 180 / Math.PI;

function normalizeHours(h: number): number {
  return ((h % 24) + 24) % 24;
}

// Read and eval the catalog array literal.
const raw = readFileSync(SOURCE, "utf-8");
const assignment = raw.replace(/^_root\.brightStarCatalog\s*=\s*/, "").replace(/;\s*$/, "");
// eslint-disable-next-line no-new-func
const catalog = new Function(`return ${assignment};`)() as Array<{
  x: number;
  y: number;
  z: number;
  r: number;
  discs: Array<{
    x: number;
    y: number;
    z: number;
    r: number;
    w0: number;
    w1: number;
    w2: number;
    w3: number;
    w4: number;
    w5: number;
    w6: number;
    w7: number;
    w8: number;
    stars: Array<{ sx: number; sy: number; mag: number }>;
  }>;
}>;

interface ExtractedStar {
  raHours: number;
  decDeg: number;
  mag: number;
}

const stars: ExtractedStar[] = [];
let totalRaw = 0;

for (const superDisc of catalog) {
  for (const sub of superDisc.discs) {
    for (const s of sub.stars) {
      totalRaw++;
      const nx = -s.sx / SPHERE_RADIUS;
      const ny = -s.sy / SPHERE_RADIUS;
      const nzSq = 1 - nx * nx - ny * ny;
      if (nzSq < 0) {
        continue; // outside the unit sphere (shouldn't happen for valid data)
      }
      const nz = Math.sqrt(nzSq);

      const wx = sub.w0 * nx + sub.w1 * ny + sub.w2 * nz;
      const wy = sub.w3 * nx + sub.w4 * ny + sub.w5 * nz;
      const wz = sub.w6 * nx + sub.w7 * ny + sub.w8 * nz;

      const raHours = normalizeHours(Math.atan2(wy, wx) * RAD_TO_HOURS);
      const decDeg = Math.asin(Math.max(-1, Math.min(1, wz))) * RAD_TO_DEG;

      stars.push({ raHours, decDeg, mag: s.mag });
    }
  }
}

// NAAP renders stars with mag <= 5.8 (naked-eye limit).
const visible = stars.filter((s) => s.mag <= 5.8);

// Stats by magnitude bin.
const bins = [0, 1, 2, 3, 4, 5, 5.8];
for (let i = 0; i < bins.length - 1; i++) {
  const lo = bins[i] ?? 0;
  const hi = bins[i + 1] ?? 0;
  const count = visible.filter((s) => s.mag > lo && s.mag <= hi).length;
  console.log(`  mag (${lo}, {hi}]: ${count}`);
}
console.log(`Total raw stars: ${totalRaw}`);
console.log(`Stars with mag <= 5.8: ${visible.length}`);

// Sort by brightness (brightest first) for rendering priority.
visible.sort((a, b) => a.mag - b.mag);

// Emit compact TS: three flat number arrays for minimal parse overhead.
const ras = visible.map((s) => +s.raHours.toFixed(3));
const decs = visible.map((s) => +s.decDeg.toFixed(2));
const mags = visible.map((s) => +s.mag.toFixed(2));

const ts = `/**
 * BrightStarCatalog.ts
 *
 * @generated by scripts/generate-bright-star-catalog.ts — do not edit by hand.
 * Source: NAAP skyMap028 Bright Star Catalog.as (decompiled), recovered to
 * equatorial coordinates via the disc rotation matrices (see the generator
 * for the math). ${visible.length} stars with visual magnitude <= 5.8.
 */
export type CatalogStar = { raHours: number; decDeg: number; mag: number };

export const BRIGHT_STAR_COUNT = ${visible.length};

/** Flat arrays — index i → star i. mag <= 5.8 (naked-eye limit, per NAAP). */
export const BRIGHT_STAR_RA_HOURS: readonly number[] = [${ras.join(",")}];

export const BRIGHT_STAR_DEC_DEG: readonly number[] = [${decs.join(",")}];

export const BRIGHT_STAR_MAG: readonly number[] = [${mags.join(",")}];
`;

writeFileSync(OUTPUT, ts);
console.log(`Wrote ${OUTPUT} (${(ts.length / 1024).toFixed(0)} KB, ${visible.length} stars)`);
